config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit]
  root 'spots#index'
  resources :spots
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spot.rb
class Spot < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def after_sign_out_path_for(resource)
    '/users/sign_in'
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  # before_action :set_map, only: [:show, :edit, :update, :destroy]
  def index
    @spots =Spot.all
    @hash = Gmaps4rails.build_markers(@maps) do |map, marker|
    marker.lat map.latitude
    marker.lng map.longitude
    marker.infowindow map.name
  end

  # def new
  # end

  # def edit
  # end

  def show
    @spot = Spot.find(params[:id])
  end

  # def search
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_header.html.haml
.header-area
#sticky-header.main-header-area.white-bg
.container-fluid.p-0
  .row.align-items-center.justify-content-between.no-gutters
    .col-xl-2.col-lg-2
      .lemom-logo
        %figure.good_logo
          = image_tag 'lemon.png'
      .logo-img
        %a{href: "index.html"}
          Weekend Citrus
    .col-xl-7.col-lg-7
      .main-menu.d-none.d-lg-block
        %nav
          %ul#navigation
            %li
              %a.active{href: ""} あんずさん
            %li
              %a{href: ""} マイページ
            %li
              %a{href: ""} 投稿する
            %li
              %a{href: ""} 検索する
            %li
              %form{action: "/search-result/"}
                %input#search-input{name: "search-key", placeholder: "1つキーワードを入力", type: "text"}/
                %input#search-buttom.fas{method: "get", type: "submit", value: ""}/
            %li
              = link_to 'サインアウト', "/users/sign_out", method: :delete
      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title App
    = csrf_meta_tags
    = csp_meta_tag
    
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+Rails.application.credentials.google_maps_api_key

    -# = javascript_include_tag src: "https://maps.googleapis.com/maps/api/js?key=Rails.application.credentials.google_maps_api_key"
    -# %script{src: "//maps.google.com/maps/api/js?key=#{Rails.application.credentials.google_maps_api_key}"}
    %script{src:"//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"}
    %script{src: '//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js'},{type: 'text/javascript'}
    = yield(:head_tags)
  %body
    = yield

app/views/spots/index.html.haml
= javascript_pack_tag 'hello_vue'
.top-container
  = render partial: 'common/header'


%p#notice= notice
%h1 Maps
%table
  %thead
    %tr
      %th Name
      %th Latitude
      %th Longitude
      %th{colspan: "3"}
  %tbody
    - @spots.each do |spot|
      %tr
        %td= spot.name
        %td= spot.latitude
        %td= spot.longitude
        %td= link_to 'Show', spot
        %td= link_to 'Edit', edit_spot_path(spot)
        %td= link_to 'Destroy', spot, method: :delete, data: { confirm: 'Are you sure?' }
%br


.map-box
  %p
    #map
    -# = image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=17&size=400x300&center=#{35.6751},#{139.763}&key=#{Rails.application.credentials.google_maps_static_api_key}", alt: "Map"
    -# = image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=17&size=400x300&markers=size:small%7Ccolor:red%7C#{35.6751},#{139.763}&key=#{Rails.application.credentials.google_maps_static_api_key}", alt: "Map"

- provide :head_tags do
  :javascript
    document.addEventListener("DOMContentLoaded", function() {
      initMap(#{35.6751}, #{35.6751})
    });

app/views/spots/new.html.haml
.wrapper
  .top-container
    = render partial: 'common/header'
  .main
    .city_img
      %figure.city_logo
        = image_tag 'city_view.png'

    %form.post_form
      %label.post_label
        %p.label-txt オススメスポット
        %input.input{type: "text"}/
        .line-box
          .line
      %label.post_label
        %p.label-txt 画像
        %input.input{type: "file"}/
        .line-box
          .line
      %label.post_label
        %p.label-txt オススメのポイント
        = text_area :text, class: 'input' 'text_area'
        .line-box
          .line
      %button{type: "submit"} 投稿する

app/views/spots/show.html.haml
.top-container
  = render partial: 'common/header'

.main
  .city_side
    %figure.building
      = image_tag 'city_side.png'

  .show_spot
    .post_label
      %h2.text-uppercase.mt-3.font-weight-bold.text-grey little star cafeの詳細
      .line-box
        .line
    .post_label
      .city_cafe
      %figure.good_cafe
        = image_tag 'stylish_cafe.png'
      .line-box
        .line
    .post_label
      %h3.text-uppercase.mt-3.font-weight-bold.text-grey みゆきさんのおすすめポイント
      %p.label-txt 代官山のオススメのカフェです。代官山駅から歩いて2分ほどと駅近。パリの街角にあるカフェのような外観に、味への期待が高まります。
      .line-box
        .line
    .box
      %button{type: "submit"} コメントを投稿する
      %button{type: "submit"}お気に入り
  
  .city_side
    %figure.building
      = image_tag 'city_side.png'

.map-box
  %p
    #map
    -# = image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=17&size=400x300&center=#{35.6751},#{139.763}&key=#{Rails.application.credentials.google_maps_static_api_key}", alt: "Map"
    -# = image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=17&size=400x300&markers=size:small%7Ccolor:red%7C#{35.6751},#{139.763}&key=#{Rails.application.credentials.google_maps_static_api_key}", alt: "Map"

- provide :head_tags do
  :javascript
    document.addEventListener("DOMContentLoaded", function() {
      initMap(#{35.6751}, #{35.6751})
    });

app/views/users/show.html.haml
.top-container
  = render partial: 'common/header'

#contatti.row
  .container.mt-5
    .row{style: "height:550px;"}
      .col-md-6.maps
        .text-green
          %h2.text-uppercase.mt-3.font-weight-bold.text-grey あんずさんのマイページ
          %i.fas.fa-phone.mt-3
          %a{href: "tel:+"} 今まで投稿したスポット

        %iframe{allowfullscreen: "", frameborder: "0", src: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11880.492291371422!2d12.4922309!3d41.8902102!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x28f1c82e908503c4!2sColosseo!5e0!3m2!1sit!2sit!4v1524815927977", style: "border:0"}
      .col-md-6
        
        
        %h2.text-uppercase.mt-3.font-weight-bold.text-grey お気に入りユーザー
        .text-grey
          %i.fas.fa-phone.mt-3
          %a{href: "tel:+"} ひなちゃん
          %br/
          %i.fas.fa-phone.mt-3
          %a{href: "tel:+"} まりちゃん
          %br/
          %i.fa.fa-envelope.mt-3
          %a{href: ""} hikariさん
          %br/
          %i.fas.fa-globe.mt-3
          RISAさん
          %br/
          -# %i.fas.fa-globe.mt-3
          -# Piazza del Colosseo, 1, 00184 Roma
          %br/
          .my-4
            %a{href: ""}
              %i.fab.fa-facebook.fa-3x.pr-4
            %a{href: ""}
              %i.fab.fa-linkedin.fa-3x